# Generated by Django 2.0 on 2017-12-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0002_auto_20171224_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='album',
            field=models.CharField(default='n/a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solo',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solo',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
