# Generated by Django 2.0 on 2017-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20171225_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default='n/a'),
            preserve_default=False,
        ),
    ]
